---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- secret.yaml
- ocirepository.yaml
- helmrepository.yaml
- helmrelease.yaml
- podmonitor.yaml
configMapGenerator:
  - name: flux-kube-state-metrics-config
    namespace: monitoring
    files:
      - kube-state-metrics-config.yaml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
  - name: flux-grafana-dashboards
    namespace: monitoring
    files:
      - dashboards/control-plane.json
      - dashboards/cluster.json
      - dashboards/logs.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
        kustomize.toolkit.fluxcd.io/substitute: disabled
configurations:
  - kustomizeconfig.yaml
