---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- doppler.yaml
- capacitor.yaml
- cloudflared.yaml
- elasticsearch.yaml
- logging.yaml
- monitoring.yaml
- tracing.yaml
- postgres.yaml
- go-template.yaml
- blog.yaml
