---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- doppler.yaml
- monitoring.yaml
- tailscale-cleanup-stale-devices.yaml
- tailscale.yaml
- capacitor.yaml
- database.yaml
- go-template.yaml
- blog.yaml
