---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- doppler.yaml
- cloudflared.yaml
- monitoring.yaml
- elastic-stack.yaml
- capacitor.yaml
- postgres.yaml
- go-template.yaml
- blog.yaml
