---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 60s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./envs/prod/prometheus
  prune: true
  wait: true
  dependsOn:
    - name: doppler
      namespace: flux-system
