---
apiVersion: v1
kind: Service
metadata:
  name: capacitor-svc
  namespace: flux-system
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: capacitor
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: capacitor
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9000
