---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    name: "{{ .Values.name }}-svc-monitor"
    release: monitoring
  name: "{{ .Values.name }}-svc-monitor"
  namespace: monitoring
spec:
  jobLabel: job
  endpoints:
    - interval: 60s
      port: metrics
      path: /metrics
  selector:
    matchLabels:
      app: "{{ .Values.name }}-svc"
  namespaceSelector:
    matchNames:
      - {{ .Values.name }}
