{{- if .Values.database.postgres.enabled }}
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: "{{ .Values.database.postgres.name }}-daily-backup"
spec:
  immediate: true
  schedule: {{ .Values.database.postgres.backupSchedule | quote }}
  backupOwnerReference: cluster
  cluster:
    name: "{{ .Values.database.postgres.name }}-pg"
{{ - end }}
