---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: prometheus-secret
  namespace: doppler-operator-system
spec:
  tokenSecret: 
    name: doppler-token-secret
  project: prod
  config: prd
  managedSecret:
    name: prometheus-secret
    namespace: prometheus
